export {default as Home } from './home'
export {default as About } from './aboutus'
export {default as Work}  from './ourwork'
export { default as Method } from './method'
export { default as Contact } from './contact'
export { default as Iyebe } from './iyebe'
export { default as Privacy } from './privacy'
export { default as Careers } from './careers'
