export {default as Navbar } from './navbar/nav'
export {default as Footer} from './footer/footer'
export {default as Work}  from './work/work'
export {default as Testimonial} from './testimonials/testimonial'
export {default as Blogs } from './blogs/blogs'