export { default as Navbar } from './nav'
export { default as Footer } from './footer'
export { default as Work } from './work'
export { default as Testimonial } from './testimonial'
export { default as Blogs } from './blogs'
export { default as Slider } from './slider'
export {  default as Brands} from './brands'